src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="category")
     */
    private $products;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="childCategories")
     */
    private $Parent;

    /**
     * @ORM\OneToMany(targetEntity=Category::class, mappedBy="Parent")
     */
    private $childCategories;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->childCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->Parent;
    }

    public function setParent(?self $Parent): self
    {
        $this->Parent = $Parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getChildCategories(): Collection
    {
        return $this->childCategories;
    }

    public function addChildCategory(self $childCategory): self
    {
        if (!$this->childCategories->contains($childCategory)) {
            $this->childCategories[] = $childCategory;
            $childCategory->setParent($this);
        }

        return $this;
    }

    public function removeChildCategory(self $childCategory): self
    {
        if ($this->childCategories->contains($childCategory)) {
            $this->childCategories->removeElement($childCategory);
            // set the owning side to null (unless already changed)
            if ($childCategory->getParent() === $this) {
                $childCategory->setParent(null);
            }
        }

        return $this;
    }
}

src/Controller/CategoryEditController.php
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\EntityManagerInterface;

class CategoryEditController extends AbstractController
{
    public function categoryedit (Request $request, $id)
    {
        $categoryManager = $this->getDoctrine()->getManager();
        $category = $categoryManager->getRepository(Category::class)->find($id);

        $childCategories=$category->getChildCategories();
        
        $form1 = $this->createForm (CategoryType::class, $category)
            ->add('save', SubmitType::class, ['label'=> 'Save changes']);
               
        $form1->handleRequest($request);
        
        if ($form1->isSubmitted()) {
            
            $categoryManager->flush();
        }
       
        $contents = $this->renderView('category_edit/category_edit.html.twig',
             [
                'form1' => $form1->createView(),
                'id'=> $id,
                'category' => $category,
                'childCategories' => $childCategories
            ],
        );
        return new Response($contents);
    }
}

templates/category_edit/category_edit.html.twig
{% extends 'base.html.twig' %}   

{% block stylesheets1 %}
    <link rel="stylesheet" href="/css/category_edit.css">
{% endblock %}

{% block content %}           

    <h1>CHANGING CATEGORIES</h1>     

    <span>You are changing the category with id {{id}}:</span><br>
        Name:  {{category.name}}  <br>
    {% if category.parent.name is defined %}
        Parent: {{category.parent.name}} <br>
    {% else %}
        Parent: without Parent <br>
    {% endif %}
    <br><br>

    <span>Enter your changes:</span><br>
    {{form(form1)}}
    <br>

    {% if childCategories is not empty %}
            
        <span>List of child categories of {{category.name}} :</span><br>

        {% for childCat in childCategories %} 
            
            <a href="{{ path('category_edit', {id: childCat.id}) }}">{{childCat.name}}</a><br>
            
        {% endfor %}

    {% else %}
        <span>List of child categories of {{category.name}} : 0</span><br>
    {% endif %}
               
    

        <button type="button"><a class="button" target="_blank" href="{{ path('category_add', {id: id}) }}">Add another child</a></button>
   
{% endblock %}